### ISSUE TITLE
PHP Warning: session_start(): Cannot start session when headers already sent 

### ISSUE THREAD

**Issue by okwasniewski** [kylephillips/favorites#146]
Hello,

I have installed the plugin everything works seamlessly but there is one problem that stops the site from responding.

04-Jan-2021 07:50:16 UTC] PHP Warning: session_start(): Cannot start session when headers already sent in /home/joganika/public_html/wp-content/plugins/favorites/app/Bootstrap.php on line 83
[04-Jan-2021 07:55:14 UTC] PHP Warning: session_start(): Cannot start session when headers already sent in /home/joganika/public_html/wp-content/plugins/favorites/app/Bootstrap.php on line 83

The error is generated over and over which causes the site to freeze and don't load.

**Comment by genesanchez** [comment]
I too have this issue.  I have found a workaround for my setup.  Since I don't use Anonymous users on my env.  I changed the Plugin Favorites settings : Users : Save Unauthenticated Favorites as  to Cookie instead of session.   It seems to solved my problem.  It may not apply to your setup. I just wanted to share my experience if you want to give it a try.

**Comment by okwasniewski** [comment]
@genesanchez  Thanks, this resolved the issue for me.

**Comment by sz-33** [comment]
Hello, if we replace 

if ( !session_id() ) session_start(); 

by

session_start(['read_and_close' => true,]);

it seems to work 

++
