### ISSUE TITLE
Get last favorited post (Callback function)

### ISSUE THREAD

**Issue by jorditost** [kylephillips/favorites#48]
Hi,

is there a way to get the post that a user just favorited, just right after the favorite button has been submitted?

The callback `favorites_after_button_submit` is returning an array of all posts that a user has favorited so far, but it would be interesting to have a function that returns only the last one (and get if the user favorited or "unfavorited" it).

I need it to integrate the favorites activity in the Activity Feed of a BuddyPress site. Any other way to implement that would be also welcome.

Thanks!

**Comment by kylephillips** [comment]
I know this is a really old question…

The next release will switch to using events rather than the callback functions (they'll still be there, just deprecated).

There will be a `favorites-updated-single` event at the document level that will pass 4 parameters: `favorites` (array of all favorites), `post_id` (of the post just favorited), `site_id`, & `status` (either 'active' or 'inactive'.
