### ISSUE TITLE
Slow admin

### ISSUE THREAD

**Issue by Saman24** [kylephillips/favorites#60]
Hello
Thank you for this plugin

but why is "admin-ajax.php" is loading so slow with this plugin?
it added 3 sec load time to my page load

and why is it loading on my home page ? i don't even have any favorite button on my home page
loading admin-ajax on every page is not really good idea when we don't even have any favorite button on those pages

can you please take a look at this please?

**Comment by kylephillips** [comment]
admin-ajax is required to get around sites with cache enabled. Nonces are used to help prevent XSS, and can't be verified correctly on cached pages. So, the nonce is generated dynamically from an ajax request on page load. Additionally, an ajax call is made to get the users favorites so that buttons can be updated and "cache-busted" as needed.

The next release will have the option to disable this on non-cached sites, just be aware that if your site is cached, and this is option disabled, things may not work correctly.
